version: '3'
services:
  users-backend:
    build: . 
    image: invista/users:0.0.10
    environment:
      DB_HOST: invista-users-db.cr6ld9unj4h4.us-east-1.rds.amazonaws.com
      DB_PORT: 5432
      DB_DATABASE: invista_users
      DB_USERNAME: postgres
      DB_PASSWORD: nfjy1994
    ports:
      - 8001:8000
